const businesses = [
    {
        id: 1, 
        category: "Baby", 
        name: "Huggies", 
        url: "https://www.huggies.com/en-us/", 
        logo: "https://dorve.com/wp-content/uploads/2021/07/huggies_logo_before_after_animation-1024x576.gif", 
    }, 
    {
        id: 2, 
        category: "Baby", 
        name: "Pampers", 
        url: "https://www.pampers.com/en-us", 
        logo: "https://mir-s3-cdn-cf.behance.net/project_modules/hd/6d01bf9840733.560db0b5e841c.jpg"
    }, 
    {
        id: 3, 
        category: "Baby", 
        name: "Luvs", 
        url: "https://www.luvsdiapers.com/en-us", 
        logo: "https://cdn.worldvectorlogo.com/logos/luvs.svg"
    }, 
    {
        id: 4, 
        category: "Baby", 
        name: "Toys R Us", 
        url: "https://www.toysrus.com/", 
        logo: "https://static.wikia.nocookie.net/bubblestand/images/e/e1/Toys-R-Us-symbol.jpg/revision/latest?cb=20200803021353"
    }, 
    {
        id: 5, 
        category: "Baby", 
        name: "Dyper", 
        url: "https://dyper.com/", 
        logo: "https://m.media-amazon.com/images/S/stores-image-uploads-na-prod/3/AmazonStores/ATVPDKIKX0DER/e2e50f0e5e98bfcb3732e929c08a0826.w800.h800.png"
    }, 
    {
        id: 6, 
        category: "Baby", 
        name: "Millie Moon", 
        url: "https://mymilliemoon.com/", 
        logo: "https://mymilliemoon.com/wp-content/themes/base/assets/svgs/Millie-Moon-Logo-Footer.svg"
    }, 
    {
        id: 7, 
        category: "Clothes", 
        name: "Gap", 
        url: "https://www.gapinc.com/en-us/", 
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Gap_logo.svg/2048px-Gap_logo.svg.png"
    }, 
    {
        id: 8, 
        category: "Clothes", 
        name: "Old Navy", 
        url: "https://oldnavy.gap.com/", 
        logo: "https://download.logo.wine/logo/Old_Navy/Old_Navy-Logo.wine.png"
    }, 
    {
        id: 9, 
        category: "Clothes", 
        name: "Uniqlo", 
        url: "https://www.uniqlo.com/us/en/", 
        logo: "https://i1.wp.com/encyclopedia.design/wp-content/uploads/2019/02/uniqlo-logo.jpeg?fit=2560%2C853"
    }, 
    {
        id: 10, 
        category: "Clothes", 
        name: "Ralph Lauren", 
        url: "https://www.ralphlauren.com/", 
        logo: "https://static.vecteezy.com/system/resources/previews/023/871/089/non_2x/ralph-lauren-brand-logo-with-name-white-symbol-clothes-design-icon-abstract-illustration-with-blue-background-free-vector.jpg", 
    }, 
    {
        id: 11, 
        category: "Clothes", 
        name: "H&M", 
        url: "https://www2.hm.com/en_us/index.html", 
        logo: "https://1000logos.net/wp-content/uploads/2017/02/Colors-of-the-HM-Logo.jpg", 
    }, 
    {
        id: 12, 
        category: "Clothes", 
        name: "Nordstrom", 
        url: "https://www.nordstrom.com/", 
        logo: "https://cdn.worldvectorlogo.com/logos/nordstrom.svg", 
    }, 
    {
        id: 13, 
        category: "Clothes", 
        name: "Levi's", 
        url: "https://www.levi.com/US/en_US/", 
        logo: "https://static.vecteezy.com/system/resources/previews/023/871/690/original/levis-brand-logo-symbol-design-clothes-fashion-illustration-with-black-background-free-vector.jpg", 
    }, 
    {
        id: 14, 
        category: "Clothes", 
        name: "Calvin Klein", 
        url: "https://www.calvinklein.us/en", 
        logo: "https://logowik.com/content/uploads/images/calvin-klein5506.jpg", 
    }, 
    {
        id: 15, 
        category: "Clothes", 
        name: "Tommy Hilfiger", 
        url: "https://usa.tommy.com/en", 
        logo: "https://static.vecteezy.com/system/resources/previews/010/994/250/non_2x/tommy-hilfiger-logo-symbol-red-and-blue-clothes-design-icon-abstract-football-illustration-with-white-background-free-vector.jpg", 
    }, 
    {
        id: 16, 
        category: "Clothes", 
        name: "Converse", 
        url: "https://www.converse.com/", 
        logo: "https://cdn.shopify.com/s/files/1/0558/6413/1764/files/Rewrite_Converse_Logo_Design_History_Evolution_0_1024x1024.jpg?v=1694703129", 
    }, 
    {
        id: 17, 
        category: "Clothes", 
        name: "OshKosh B'gosh", 
        url: "https://www.oshkosh.com/", 
        logo: "https://1000logos.net/wp-content/uploads/2021/05/Oshkosh-logo.png", 
    }, 
    {
        id: 18, 
        category: "Clothes", 
        name: "Kohl's", 
        url: "https://www.kohls.com/", 
        logo: "https://1000logos.net/wp-content/uploads/2018/11/Kohls-Logo.jpg", 
    }, 
    {
        id: 19, 
        category: "Clothes", 
        name: "Carter's", 
        url: "https://www.carters.com/", 
        logo: "https://play-lh.googleusercontent.com/cFDyX1Dk0iG9hzgUVOBHs9W5Gn_kivZuJYXfELWFrhHPeaMenn500tArNLhDI-ciCQ", 
    }, 
    {
        id: 20, 
        category: "Education", 
        name: "Office Depot", 
        url: "https://www.officedepot.com/", 
        logo: "https://static.wikia.nocookie.net/theoffice/images/2/25/Office_Depot_Logo.jpg/revision/latest?cb=20180718163426", 
    }, 
    {
        id: 21, 
        category: "Education", 
        name: "Staples", 
        url: "https://www.staples.com/", 
        logo: "https://dpcre.com/wp-content/uploads/2017/04/staples-logo.png", 
    }, 
    {
        id: 22, 
        category: "Education", 
        name: "Barnes and Noble", 
        url: "https://www.barnesandnoble.com/", 
        logo: "https://www.mediaplace.us/wp-content/uploads/2018/08/Barnes-Noble-logo.png", 
    }, 
    {
        id: 23, 
        category: "Education", 
        name: "Kaplan", 
        url: "https://www.kaplanco.com/", 
        logo: "https://cdn.freebiesupply.com/logos/large/2x/kaplan-logo-svg-vector.svg", 
    }, 
    {
        id: 24, 
        category: "Education", 
        name: "Scholastic", 
        url: "https://www.scholastic.com/home", 
        logo: "https://static.wikia.nocookie.net/nickelodeon/images/5/51/Scholasticlogo.png/revision/latest?cb=20211026095802", 
    }, 
    {
        id: 25, 
        category: "Education", 
        name: "Sylvan Learning", 
        url: "https://www.sylvanlearning.com/", 
        logo: "https://upload.wikimedia.org/wikipedia/commons/3/36/US_2016_SYLVAN_LOGO.jpg", 
    }, 
    {
        id: 26, 
        category: "Education", 
        name: "Udemy", 
        url: "https://www.udemy.com/", 
        logo: "https://about.udemy.com/wp-content/themes/wp-about-v4/assets/images/fallbackimage.jpg", 
    }, 
    {
        id: 27, 
        category: "Education", 
        name: "Coursera", 
        url: "https://www.coursera.org/", 
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Coursera-Logo_600x600.svg/2048px-Coursera-Logo_600x600.svg.png", 
    }, 
    {
        id: 28, 
        category: "Education", 
        name: "Chegg", 
        url: "https://www.chegg.com/", 
        logo: "https://logowik.com/content/uploads/images/chegg8545.jpg", 
    }, 
    {
        id: 29, 
        category: "Extracurricular", 
        name: "Dick's Sporting Goods", 
        url: "https://www.dickssportinggoods.com/", 
        logo: "https://yt3.googleusercontent.com/VGR5OgHD3gJFxRje1vfg_D-SQGkPH8x2R-e8f1sFMs2cVLeS3FhYx-6mRxskC8ASTD2uPHpIiXM=s900-c-k-c0x00ffffff-no-rj", 
    }, 
    {
        id: 30, 
        category: "Extracurricular", 
        name: "Big 5 Sporting Goods", 
        url: "https://www.big5sportinggoods.com/store/", 
        logo: "https://s3-symbol-logo.tradingview.com/big-5-sporting-goods--600.png", 
    }, 
    {
        id: 31, 
        category: "Extracurricular", 
        name: "REI", 
        url: "https://www.rei.com/", 
        logo: "https://cdn.freebiesupply.com/logos/large/2x/rei-logo-png-transparent.png", 
    }, 
    {
        id: 32, 
        category: "Extracurricular", 
        name: "Guitar Center", 
        url: "https://www.guitarcenter.com/", 
        logo: "https://yt3.googleusercontent.com/xbWzUnNi9ARyWvPGE_NzyPLWgVaCE5IbvkXoxIhfheoXmA2V-FcLTZR5S7ubTfMxdO-bCTid=s900-c-k-c0x00ffffff-no-rj", 
    }, 
    {
        id: 33, 
        category: "Extracurricular", 
        name: "Nike", 
        url: "https://www.nike.com/", 
        logo: "https://i.insider.com/53d29d5c6bb3f7a80617ada8?width=800&format=jpeg&auto=webp", 
    }, 
    {
        id: 34, 
        category: "Extracurricular", 
        name: "Adidas", 
        url: "https://www.adidas.com/us", 
        logo: "https://cdn.sanity.io/images/kts928pd/production/254e805fc27df499af428dfa9fa9cdf9c119a7a3-1280x720.png", 
    }, 
    {
        id: 35, 
        category: "Extracurricular", 
        name: "Gatorade", 
        url: "https://www.gatorade.com/", 
        logo: "https://i.pinimg.com/originals/b5/55/d4/b555d4b0e3865740089caceb23d58e77.jpg", 
    }, 
    {
        id: 36, 
        category: "Extracurricular", 
        name: "Play it Again Sports", 
        url: "https://www.playitagainsports.com/", 
        logo: "https://marvel-b1-cdn.bc0a.com/f00000000211790/cms-ordercloud.azureedge.net/assets-9f79a4a6-4834-4962-98f3-6e4b59e2eacc/408c6f10-3bac-4f98-af9f-7d3b4a7ebc18", 
    }, 
    {
        id: 37, 
        category: "Home", 
        name: "Ace Hardware", 
        url: "https://www.acehardware.com/", 
        logo: "https://1000logos.net/wp-content/uploads/2021/05/ACE-Hardware-logo.png", 
    }, 
    {
        id: 38, 
        category: "Home", 
        name: "Bed Bath and Beyond", 
        url: "https://www.bedbathandbeyond.com/", 
        logo: "https://www.infinityinstruments.com/wp-content/uploads/Color-Bed-Bath-and-Beyond-Logo.jpg", 
    }, 
    {
        id: 39, 
        category: "Home", 
        name: "Home Depot", 
        url: "https://www.homedepot.com/", 
        logo: "https://i0.wp.com/elkhorn.makerfaire.com/wp-content/uploads/sites/231/2018/01/Home-Depot-Logo.png?fit=781%2C781&ssl=1", 
    }, 
    {
        id: 40, 
        category: "Home", 
        name: "Lowe's", 
        url: "https://www.lowes.com/", 
        logo: "https://mobileimages.lowes.com/marketingimages/2b928fb1-a997-4a2c-8824-4b149b75b8ef/lowes-logos-dp18-332098-og.jpg", 
    }, 
    {
        id: 41, 
        category: "Home", 
        name: "Home Goods", 
        url: "https://www.homegoods.com/", 
        logo: "https://www.homegoods.com/img/header/logo.svg", 
    }, 
    {
        id: 42, 
        category: "Home", 
        name: "Sur La Table", 
        url: "https://www.surlatable.com/", 
        logo: "https://mma.prnewswire.com/media/962370/Sur_La_Table_Logo.jpg?p=facebook", 
    }, 
    {
        id: 43, 
        category: "Home", 
        name: "Crate and Barrel", 
        url: "https://www.crateandbarrel.com/", 
        logo: "https://searchlogovector.com/wp-content/uploads/2018/05/crate-barrel-logo-vector.png", 
    }, 
    {
        id: 44, 
        category: "Home", 
        name: "Ikea", 
        url: "https://www.ikea.com/us/en/", 
        logo: "https://static.dezeen.com/uploads/2019/04/ikea-logo-new-sq-1.jpg", 
    }, 
    {
        id: 45, 
        category: "Home", 
        name: "Wayfair", 
        url: "https://www.wayfair.com/", 
        logo: "https://1000logos.net/wp-content/uploads/2023/10/Wayfair-Logo.png", 
    }, 
    {
        id: 46, 
        category: "Home", 
        name: "Wayfair", 
        url: "https://www.wayfair.com/", 
        logo: "https://1000logos.net/wp-content/uploads/2023/10/Wayfair-Logo.png", 
    }, 
    {
        id: 47, 
        category: "Home", 
        name: "Williams Sonoma", 
        url: "https://www.williams-sonoma.com/?cm_type=gnav", 
        logo: "https://static.wikia.nocookie.net/americangirl/images/7/7a/Williams-Sonoma.png/revision/latest?cb=20170103102659", 
    }, 
    {
        id: 48, 
        category: "Home", 
        name: "Pottery Barn", 
        url: "https://www.potterybarn.com/", 
        logo: "https://static.wikia.nocookie.net/usastorefanon/images/3/36/Pottery-barn-logo.png/revision/latest?cb=20190103221046", 
    }, 
    {
        id: 49, 
        category: "Miscellaneous", 
        name: "Target", 
        url: "https://www.target.com/", 
        logo: "https://1000logos.net/wp-content/uploads/2017/06/Target-logo-1.png", 
    }, 
    {
        id: 50, 
        category: "Miscellaneous", 
        name: "Walmart", 
        url: "https://www.walmart.com/", 
        logo: "https://1000logos.net/wp-content/uploads/2017/05/Emblem-Walmart.jpg", 
    }, 
    {
        id: 51, 
        category: "Miscellaneous", 
        name: "Best Buy", 
        url: "https://www.bestbuy.com/", 
        logo: "https://cdn.worldvectorlogo.com/logos/best-buy.svg", 
    }, 
    {
        id: 52, 
        category: "Miscellaneous", 
        name: "Vons", 
        url: "https://www.vons.com/", 
        logo: "https://download.logo.wine/logo/Vons/Vons-Logo.wine.png", 
    }, 
    {
        id: 53, 
        category: "Miscellaneous", 
        name: "CVS", 
        url: "https://www.cvs.com/", 
        logo: "https://1000logos.net/wp-content/uploads/2021/07/CVS-Health-Logo.png", 
    }, 
    {
        id: 54, 
        category: "Miscellaneous", 
        name: "Rite Aid", 
        url: "https://www.riteaid.com/", 
        logo: "https://cloudfront-us-east-1.images.arcpublishing.com/advancelocal/B7NQKWV5SZD3TP63FIZITMPVZY.jpg", 
    }, 
    {
        id: 55, 
        category: "Miscellaneous", 
        name: "PetSmart", 
        url: "https://www.petsmart.com/", 
        logo: "https://download.logo.wine/logo/PetSmart/PetSmart-Logo.wine.png", 
    },
    {
        id: 56, 
        category: "Miscellaneous", 
        name: "Whole Foods Market", 
        url: "https://www.wholefoodsmarket.com/", 
        logo: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Whole_Foods_Market_201x_logo.svg", 
    },
    {
        id: 57, 
        category: "Miscellaneous", 
        name: "Amazon", 
        url: "https://www.amazon.com/", 
        logo: "https://www.hatchwise.com/wp-content/uploads/2022/05/amazon-logo-1024x683.png", 
    },
]

module.exports = businesses